{
 "title": "Mikrotik Exporter",
 "description": "Mikrotik RouterOS metrics",
 "tags": [
  "dashboard",
  "mikrotik"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(mikrotik_system_uptime,address)"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Identity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "sysName{instance=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "legendFormat": "{{sysName}}",
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mikrotik_system_uptime{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "DHCP leases",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mikrotik_dhcp_leases_active_count{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "DHCP leases" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "expr": "mikrotik_system_cpu_load{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "CPU 1 load" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mikrotik_system_total_memory{address=\"$node\"} - mikrotik_system_free_memory{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System version and hw",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mikrotik_system_uptime{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "legendFormat": "{{version}} on {{boardname}}",
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "expr": "mikrotik_system_cpu_load{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "CPU 1 load" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mikrotik_system_total_hdd_space{address=\"$node\"} - mikrotik_system_free_hdd_space{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Memory" },
     "expr": "mikrotik_system_total_hdd_space{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Total memory" },
     "legendFormat": "Total memory",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "ICMP response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "s", "label": "ICMP response time" }
   ],
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "expr": "probe_icmp_duration_seconds{instance=\"$node\",phase=\"rtt\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "ICMP response time" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "1-avg_over_time(probe_success{instance=\"$node\",job=\"blackbox\"}[1m])",
     "legendFormat": "ICMP loss"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mikrotik_interface_rx_byte{address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In - {{ interface }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Network" },
     "expr": "rate(mikrotik_interface_tx_byte{address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Outgoing traffic on interface ether1-gateway"
     },
     "legendFormat": "Out - {{ interface }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "mikrotik_dhcp_leases_metrics{address=\"$node\"}"
    }
   ]
  },
  { "title": "Interface status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mikrotik_interface_rx_error{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "/errors on interface/" },
     "legendFormat": "InErrors {{interface}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mikrotik_interface_tx_error{address=\"$node\"}",
     "legendFormat": "Out Errors {{interface}}"
    }
   ]
  },
  {
   "title": "Interface status (operational)",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "mikrotik_monitor_status{address=\"$node\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Interface  rate",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "mikrotik_monitor_rate{address=\"$node\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Wireless",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device traffic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "application": { "filter": "Wireless" },
       "expr": "-rate(mtxrWlRtabRxBytes{instance=\"$node\"}[4m])",
       "functions": [
        {
         "def": {
          "category": "Transform",
          "defaultParams": [
           100
          ],
          "name": "scale",
          "params": [
           {
            "name": "factor",
            "options": [
             100,
             0.01,
             10,
             -1
            ],
            "type": "float"
           }
          ]
         },
         "params": [ "8" ],
         "text": "scale(8)"
        }
       ],
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/Incoming traffic/" },
       "legendFormat": "RX {{mtxrWlRtabAddr}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Wireless" },
       "expr": "rate(mtxrWlRtabTxBytes{instance=\"$node\"}[4m])",
       "functions": [
        {
         "def": {
          "category": "Transform",
          "defaultParams": [
           100
          ],
          "name": "scale",
          "params": [
           {
            "name": "factor",
            "options": [
             100,
             0.01,
             10,
             -1
            ],
            "type": "float"
           }
          ]
         },
         "params": [ "8" ],
         "text": "scale(8)"
        }
       ],
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/Outgoing traffic/" },
       "legendFormat": "TX {{mtxrWlRtabAddr}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Wireless" },
       "expr": "-rate(mtxrWlCMRtabRxBytes{instance=\"$node\"}[4m])",
       "functions": [
        {
         "def": {
          "category": "Transform",
          "defaultParams": [
           100
          ],
          "name": "scale",
          "params": [
           {
            "name": "factor",
            "options": [
             100,
             0.01,
             10,
             -1
            ],
            "type": "float"
           }
          ]
         },
         "params": [ "8" ],
         "text": "scale(8)"
        }
       ],
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/Incoming traffic/" },
       "legendFormat": "RX {{mtxrWlCMRtabAddr}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Wireless" },
       "expr": "rate(mtxrWlCMRtabTxBytes{instance=\"$node\"}[4m])",
       "functions": [
        {
         "def": {
          "category": "Transform",
          "defaultParams": [
           100
          ],
          "name": "scale",
          "params": [
           {
            "name": "factor",
            "options": [
             100,
             0.01,
             10,
             -1
            ],
            "type": "float"
           }
          ]
         },
         "params": [ "8" ],
         "text": "scale(8)"
        }
       ],
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/Outgoing traffic/" },
       "legendFormat": "TX {{mtxrWlCMRtabAddr}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "SSID",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 57 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "application": { "filter": "Wireless" },
       "expr": "mtxrWlApSsid{instance=\"$node\",ifDescr=\"wlan1\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "AP SSID" },
       "legendFormat": "{{mtxrWlApSsid}}",
       "mode": 2,
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "AP noise floor",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 57 },
     "format": "dB",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Wireless" },
       "expr": "mtxrWlApNoiseFloor{instance=\"$node\",ifDescr=\"wlan1\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "AP noise floor" },
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "AP frequency",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 60 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "application": { "filter": "Wireless" },
       "expr": "mtxrWlApBand{instance=\"$node\",ifDescr=\"wlan1\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "AP frequency" },
       "legendFormat": "{{mtxrWlApBand}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "AP client count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 60 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Wireless" },
       "expr": "mtxrWlRtabEntryCount{instance=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "AP client count" },
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "CAPsMAN client count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 60 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "Wireless" },
       "expr": "mtxrWlCMRtabEntryCount{instance=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "AP client count" },
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Wireless Signal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Signal strength",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "application": { "filter": "Wireless" },
       "expr": "mtxrWlRtabStrength{instance=\"$node\"}",
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Signal strength \\((.*)\\)/",
          "$1"
         ],
         "text": "replaceAlias(/Signal strength \\((.*)\\)/, $1)"
        }
       ],
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/Signal strength/" },
       "legendFormat": "{{mtxrWlRtabAddr}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Wireless" },
       "expr": "mtxrWlCMRtabRxStrength{instance=\"$node\"}",
       "functions": [
        {
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Signal strength \\((.*)\\)/",
          "$1"
         ],
         "text": "replaceAlias(/Signal strength \\((.*)\\)/, $1)"
        }
       ],
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/Signal strength/" },
       "legendFormat": "{{mtxrWlCMRtabAddr}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Signal strength heatmap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
     "targets": [
      {
       "application": { "filter": "Wireless" },
       "expr": "mtxrWlRtabStrength{instance=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/Signal strength/" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "application": { "filter": "Wireless" },
       "expr": "mtxrWlCMRtabRxStrength{instance=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/Signal strength/" },
       "options": {
        "showDisabledItems": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Rx signal strength over channels",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "application": { "filter": "Wireless" },
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/Rx signal strength for Ch/" },
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Signal to noise",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "dB" }
     ],
     "targets": [
      {
       "application": { "filter": "Wireless" },
       "expr": "mtxrWlRtabSignalToNoise{instance=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": { "filter": "/Signal to noise/" },
       "legendFormat": "{{mtxrWlRtabAddr}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  }
 ]
}